services:
  db:
    image: postgres:latest
    container_name: postgres-book-store-prod
    restart: unless-stopped
    env_file: ./book-store-backend/.env.prod
    ports:
      - "9999:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  book-store-backend:
    container_name: book-store-backend-prod
    restart: unless-stopped
    build:
      context: ./book-store-backend
    ports:
      - "4000:4000"
    env_file: ./book-store-backend/.env.prod
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/data
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000"]
      interval: 5s
      timeout: 5s
      retries: 10

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-book-store-prod
    restart: unless-stopped
    env_file: ./book-store-search-engine/.env.prod
    ports:
      - "6333:6333"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - qdrant_data:/qdrant/storage:z 
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-book-store-prod
    restart: unless-stopped
    env_file: ./book-store-search-engine/.env.prod
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  book-store-search-engine:
    build: 
      context: ./book-store-search-engine
    container_name: book-store-search-engine-prod
    restart: unless-stopped
    ports:
    - "50051:50051"
    env_file: ./book-store-search-engine/.env.prod
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "grpc_healthcheck.py"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s
    
  book-store-search-engine-seed:
    build: 
      context: ./book-store-search-engine
    container_name: book-store-search-engine-seed
    env_file: ./book-store-search-engine/.env.prod
    command: python -m seeds.add_data_to_qdrant
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
      book-store-backend:
        condition: service_healthy
    restart: "no" 

  book-store-frontend:
    container_name: book-store-frontend-prod
    restart: unless-stopped
    build:
      context: ./book-store-frontend
      args:
        - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    env_file: ./book-store-frontend/.env.prod
    environment:
      - NODE_ENV=production
    depends_on:
      book-store-backend:
        condition: service_healthy
      book-store-search-engine:
        condition: service_healthy

volumes:
  pgdata:
  redis_data:
  qdrant_data: