services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant-book-store-local
    restart: unless-stopped
    env_file: .env.prod
    # depends_on:
    #   db:
    #     condition: service_healthy
    ports:
      - "${QDRANT_PORT}:6333"    # REST API
      - "${QDRANT_GRPC_PORT}:6334"  # gRPC API
    volumes:
      - qdrant_data:/qdrant/storage:z 
    healthcheck:
      test:
        - CMD-SHELL
        - bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1
      interval: 5s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis-book-store-local
    restart: unless-stopped
    env_file: .env.prod
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  book-store-search-engine:
    build: 
      context: .
    container_name: book-store-search-engine-local
    ports:
      - "50051:50051"
    env_file: .env.prod
    depends_on:
      qdrant:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "grpc_healthcheck.py"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 5s

    networks:
      - book-store-backend_default
      - default

volumes:
  qdrant_data:
  redis_data:

networks:
  default:
    external: false
  book-store-backend_default:
    external: true
